#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SafeTrip.Droid.Resource", IsApplication=true)]

namespace SafeTrip.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int DefaultButton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int temppanicbutton = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int WarningButton = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int HoldMyHand = 2131165186;
			
			// aapt resource value: 0x7f070016
			public const int PinNumber = 2131165206;
			
			// aapt resource value: 0x7f070003
			public const int SafeTripButton = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int addFromAddressBookButton = 2131165196;
			
			// aapt resource value: 0x7f070015
			public const int button2 = 2131165205;
			
			// aapt resource value: 0x7f070018
			public const int container = 2131165208;
			
			// aapt resource value: 0x7f070004
			public const int editText1 = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int editText2 = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int editText3 = 2131165190;
			
			// aapt resource value: 0x7f070014
			public const int emailEditText = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int finishRecordingButton = 2131165207;
			
			// aapt resource value: 0x7f07000e
			public const int firstNameEditText = 2131165198;
			
			// aapt resource value: 0x7f070001
			public const int imageButton1 = 2131165185;
			
			// aapt resource value: 0x7f070010
			public const int lastNameEditText = 2131165200;
			
			// aapt resource value: 0x7f070019
			public const int menu_add = 2131165209;
			
			// aapt resource value: 0x7f070005
			public const int myButton = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int myButton2 = 2131165192;
			
			// aapt resource value: 0x7f070012
			public const int phoneNumberEditText = 2131165202;
			
			// aapt resource value: 0x7f070009
			public const int recordVideoButton = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int textView1 = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int textView2 = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int textView5 = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int textView6 = 2131165203;
			
			// aapt resource value: 0x7f070000
			public const int texture = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int timerButton = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int timerText = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int fragment_camera2_video = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int HomeScreen = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ModifyContactLayout = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int RecordVideo = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int AddMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int finishRecordingButton = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int record = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int recordVideo = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int sms = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int stop = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
