#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SafeTrip.Droid.Resource", IsApplication=true)]

namespace SafeTrip.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::SafeTrip.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::SafeTrip.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::SafeTrip.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::SafeTrip.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::SafeTrip.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::SafeTrip.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::SafeTrip.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::SafeTrip.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::SafeTrip.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::SafeTrip.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::SafeTrip.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::SafeTrip.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::SafeTrip.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::SafeTrip.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::SafeTrip.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::SafeTrip.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::SafeTrip.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::SafeTrip.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::SafeTrip.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::SafeTrip.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::SafeTrip.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::SafeTrip.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::SafeTrip.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::SafeTrip.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::SafeTrip.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::SafeTrip.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::SafeTrip.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::SafeTrip.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::SafeTrip.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::SafeTrip.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::SafeTrip.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::SafeTrip.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::SafeTrip.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::SafeTrip.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::SafeTrip.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::SafeTrip.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::SafeTrip.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::Auth0.SDK.Resource.String.library_name = global::SafeTrip.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int DefaultButton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_errorstatus = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_successstatus = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int roundedbg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int roundedbgdark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int temppanicbutton = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int WarningButton = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001c
			public const int PinNumber = 2131165212;
			
			// aapt resource value: 0x7f070010
			public const int addFromAddressBookButton = 2131165200;
			
			// aapt resource value: 0x7f07001e
			public const int container = 2131165214;
			
			// aapt resource value: 0x7f070008
			public const int editText1 = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int editText2 = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int editText3 = 2131165194;
			
			// aapt resource value: 0x7f070018
			public const int emailEditText = 2131165208;
			
			// aapt resource value: 0x7f07001d
			public const int finishRecordingButton = 2131165213;
			
			// aapt resource value: 0x7f070012
			public const int firstNameEditText = 2131165202;
			
			// aapt resource value: 0x7f070002
			public const int holdMyHandButton = 2131165186;
			
			// aapt resource value: 0x7f070014
			public const int lastNameEditText = 2131165204;
			
			// aapt resource value: 0x7f070006
			public const int loadingImage = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int loadingProgressBar = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int loadingProgressWheel = 2131165191;
			
			// aapt resource value: 0x7f070023
			public const int main_activity_menu = 2131165219;
			
			// aapt resource value: 0x7f070022
			public const int menu_add = 2131165218;
			
			// aapt resource value: 0x7f070009
			public const int myButton = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int myButton2 = 2131165196;
			
			// aapt resource value: 0x7f070001
			public const int panicButton = 2131165185;
			
			// aapt resource value: 0x7f070016
			public const int phoneNumberEditText = 2131165206;
			
			// aapt resource value: 0x7f07001a
			public const int pinEditText = 2131165210;
			
			// aapt resource value: 0x7f07000d
			public const int recordVideoButton = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int safeTripButton = 2131165187;
			
			// aapt resource value: 0x7f070019
			public const int saveContactButton = 2131165209;
			
			// aapt resource value: 0x7f07001f
			public const int settings_emergency_contacts_button = 2131165215;
			
			// aapt resource value: 0x7f070021
			public const int settings_sign_out_button = 2131165217;
			
			// aapt resource value: 0x7f070020
			public const int settings_update_pin_number_button = 2131165216;
			
			// aapt resource value: 0x7f070011
			public const int textView1 = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int textView2 = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int textView5 = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int textView6 = 2131165207;
			
			// aapt resource value: 0x7f070005
			public const int textViewStatus = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int texture = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int timerButton = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int timerText = 2131165199;
			
			// aapt resource value: 0x7f07001b
			public const int verifyPinButton = 2131165211;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int fragment_camera2_video = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int HomeScreen = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int loading = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int loadingimage = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int loadingprogress = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Main = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ModifyContactLayout = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int PinLayout = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int RecordVideo = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int SettingsLayout = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int AddMenu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MainActivityMenu = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int app_name = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int finishRecordingButton = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int record = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int recordVideo = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int sms = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int stop = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
